### ISSUE TITLE
What all data should be displayed when the user clicks on an Event in Schedule List?

### ISSUE THREAD

**Issue by batraabhishek** [fossasia/fossasia-companion-android#12]
Current Fosdem App displays - **Title, Start time, End time, Venue, Speaker, Category, Detailed information**. Let the **organizers** decide what all data is available and feasible to display when an event in schedule is clicked. Accordingly the model, spreadsheet structure, database structure and layout will differ.  

Here is the screenshot from current **FOSDEM** app

![ak8mf8yv7cmq-ta5kb9ecg_s2ztmnt8znizvdhdqus8m](https://cloud.githubusercontent.com/assets/3257840/6313322/66dc6786-b9ca-11e4-87da-f52c4aa9eff4.jpg)

**Comment by mananwason** [comment]
Yeah we can let organizers decide whatever they want to show out of all the possible fields and if they don't want to show some field we can just keep it NULL and all NULL fields can be hidden.

**Comment by batraabhishek** [comment]
@mananwason That sounds great and flexible :) , @mariobehling your call?

**Comment by mariobehling** [comment]
@batraabhishek @mananwason Sounds good. Great progress!
