### ISSUE TITLE
Graphic assets for Fossasia Companion App?

### ISSUE THREAD

**Issue by batraabhishek** [fossasia/fossasia-companion-android#15]
We need good graphics assets for the application including splash screen, icons, color scheme etc. And it would be great if we can have some promo graphics that can be uploaded to play store with the app.

**Comment by mariobehling** [comment]
Who can help with that?

**Comment by mananwason** [comment]
What kind of graphics do we need for the splash screen?

**Comment by mariobehling** [comment]
Please use the FOSSASIA logo. Some artwork is here https://drive.google.com/folderview?id=0B4n_k1amQnpya3hZSzlvUjhzWFU&usp=drive_web

**Comment by mananwason** [comment]
I'll do it. Just the logo for 5 secs, is it fine?

**Comment by mariobehling** [comment]
Actually, there is no need to make people wait for any reason. If you can start the app in less than a second and the start screen is shown for an extremely short time, just do this. Start screen just lets people look at something while the app starts.

**Comment by mananwason** [comment]
Cool I'll do it under 1 second

**Comment by batraabhishek** [comment]
I would like to something here. I have already implemented a splash screen. There is only need to provide a cool and nice looking background related to Fossasia. Also, please don't fix a constant time for splash. In the splash screen, we are checking if the database is already present, if not it is downloaded from the Internet. Also, if the data is outdated, it is re-downloaded. So Its better to display Splash screen only for the time networks calls are taking place, and data is fetched.

**Comment by batraabhishek** [comment]
Since current artwork is in red. How about changing the app theme to red. 
Here is a screenshot

![redred](https://cloud.githubusercontent.com/assets/3257840/6446385/d38021c6-c130-11e4-9450-a0a63be6133d.jpg)

**Comment by mariobehling** [comment]
Yes, looks great. Thanks

**Comment by batraabhishek** [comment]
@mananwason Hey, shall I take up this task, only If you haven't spent much work this. I don't want your work to get wasted :) Thanks @mariobehling Shall we inform the organizers so that they can start updating the database. They will need some documentation for entering data into spreadsheet (like date, time format etch). We are almost done here with the app. Only bookmarks and Live events is left. So can we set a target for release 1.0 by the end of this week?

**Comment by mananwason** [comment]
@batraabhishek  I thought you had implemented the splash screen, so I started working on other minor things and the map. I couldn't do much work due to my exams and stuff. So, if you have a working model, you can start it, I can help, if you want. :D
