### ISSUE TITLE
Change map to FOSSASIA location map

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia-companion-android#2]

**Comment by mariobehling** [comment]
@ty221 Would you like to work on this companion and help to adapt it for FOSSASIA?

**Comment by ty221** [comment]
@mariobehling yes sure! I will work on this project tomorrow

**Comment by todipratik** [comment]
@mariobehling I have changed the location to **FOSSASIA 15** venue but what about the image that is present in **Map**. Do you have any similar campus map for **FOSSASIA 15**?

**Comment by mariobehling** [comment]
Yes, we will have a map, but maybe it is only ready one week before the event.

**Comment by todipratik** [comment]
so for now can we leave the screen blank ?

**Comment by mariobehling** [comment]
Here is a screenshot of the map. Maybe we can use this as a placeholder until we have sth better.
Cut it to other dimensions if needed
![fossasia15-location](https://cloud.githubusercontent.com/assets/1583873/6246445/546c8774-b769-11e4-84cd-21dd2dde5534.png)

**Comment by todipratik** [comment]
done in commit #7 
![screenshot_2015-02-18-17-59-10](https://cloud.githubusercontent.com/assets/6842317/6247301/d94773ee-b798-11e4-9618-7ef6c1f99eaf.png)

**Comment by ty221** [comment]
Seems to be ok now, however I am not sure should we close this issue or keep it open. Let us wait for @mariobehling opinion.

**Comment by mananwason** [comment]
If we are not using a customised map of the venue, shouldn't we just use google maps api showing the venue, not just the screenshot. I think that would be better. @mariobehling @ty221 ?

**Comment by todipratik** [comment]
@mananwason the app is already linked to Google Maps. See the navigation button in action bar of the above screenshot.
The present screenshot would be replaced with a image at a later point of time that would show the inside venue in more detail.

**Comment by mananwason** [comment]
@todipratik I saw the navigation button but thought that it would be more interactive if we had the maps in the app itself. No dependence on the maps application.
 We can put markers on the map itself to show details of the venue.

**Comment by todipratik** [comment]
I think markers on map wouldn't provide that feel what a custom image would. It won't be possible to show inside places of the venue clearly.
However you can wait for the opinion of @mariobehling and @ty221.

**Comment by mananwason** [comment]
apart from markers we can add different boundaries as well, to distinguish different areas and section. But let @mariobehling and @ty221 give their opinions first.

**Comment by mariobehling** [comment]
The original Fosdem app works well as an offline app and the map picture is always available offline. At an event, when hundreds of people try to go online over Wifi, it can become difficult to actually go online at times.

Maybe we could use the option of showing an offline map and a small button with an online map with markers?

What other options could be there?

**Comment by mananwason** [comment]
@mariobehling I'm saying that we should use Google maps api, so the going online part isn't very difficult but then also there is this nice property of google maps api that it caches the map when it is opened for the first time. So you have to open the map just once at the venue, so I don't think this would be a problem.  
 This is an application I made, build and try this.
https://github.com/mananwason/Map-Application

Also, I there is a provision in maps api v2 to actually store the tiles by ourselves in the apk itself, we can do that maybe.
What do you think?

**Comment by batraabhishek** [comment]
@mananwason Google Maps API v2 allows using Map Overlay Tiles from app assets. So we will have to save tiles of the venue at different zoom level. Just a suggestion though. :)

**Comment by mananwason** [comment]
@batraabhishek I know that. I was just saying that if we have to due to the wifi constraints, then we can save the tiles but most probably I think that there should be no need. Let @mariobehling @ty221 suggest something.

**Comment by mariobehling** [comment]
@mananwason Sounds great, with the offline map. Did not know about the offline function. It sounds like a very good idea. I hope we can implement that with OpenStreetMap at a later time as well.

**Comment by mananwason** [comment]
@mariobehling I didn't know about offline function in OpenStreetMap. So should we implement it right now or screenshot works fine ?

**Comment by mananwason** [comment]
@mariobehling kindly reply

**Comment by mariobehling** [comment]
@mananwason Sorry, for late reply. Let's just go for Google Maps and have a working version. I did not mean, that OSM has offline maps. Maybe they have. I do not know. Let's follow up on this later. It would be great, if you guys just implement the way you suggested above. Having tiles as a way to handle the offline/online question is great. Let's go for it! :-)

**Comment by mananwason** [comment]
@mariobehling it's okay. I'll start right on the implementation.

**Comment by mananwason** [comment]
@mariobehling I am almost done with the map. Just one question. How should we keep the map - Satellite, hybrid, normal or terrain.

**Comment by mariobehling** [comment]
Awesome! Just normal is perfect. My biggest q. is will we be able to import the data from the current spreadsheet format we used this year, but this should be discussed in the other thread, I guess.

**Comment by mananwason** [comment]
I am not quite sure about it. I'll just get started on it. As soon as I figure something I'll post it on the thread.
P.s. -  I had a question. Will you be getting the internal map as well? If so, we should make a provision to see that as well.

**Comment by batraabhishek** [comment]
Integrated Google Maps, need to add markers accordingly though. :)
