### ISSUE TITLE
Where to release the app?

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia-companion-android#21]
1) What are the steps to release the app on the Android market and on Fdroid?
2) Could you provide an apk here on github?

**Comment by ty221** [comment]
Hi @mariobehling 

To publish app on Google Play (former Android Market) you need to join Google Play Developer Program - there is one-time fee $25 (can be paid using Google Wallet). When you pay it you get access to Google Play Developer Console and possibilty to send your application.

I do not know the procedure in case of Fdroid.

I have already account with access to Google Play Developer Program, if you won't mind that there will be my name as an author (of course, there will be written this is authored by our community) I can publish it from my account.

Question 2) referrs rather to our collaborators :)

**Comment by batraabhishek** [comment]
For publishing on play store we need a play store account. Then we need to sign the app, first time signing will generate a key file. That key file must be preserved for further updating the app on Play Store. No idea about Fdroid though. 

Yes, I will commit the APK.

**Comment by ty221** [comment]
Yes, @batraabhishek is true, I forgot to tell that the developer with Google Play account has to sign the APK file. If @batraabhishek commits it, I can sign it with my key.

**Comment by mariobehling** [comment]
It would be great to get an organization account for FOSSASIA and publish other apps over this as well. Is it possible?

**Comment by ty221** [comment]
@mariobehling Yes. We just need to create Google Account for FOSSASIA and pay fee $25 (or ask them for sponsorship...)

**Comment by batraabhishek** [comment]
I will finish the app in few hours and commit the APK here. Bookmarks and live event still remaining to fix

**Comment by ty221** [comment]
@mariobehling thank you for creating account on GPDC. @batraabhishek @mariobehling please let me know when to publish app
