### ISSUE TITLE
Application description and summary on Google Play (+screenshots)

### ISSUE THREAD

**Issue by ty221** [fossasia/fossasia-companion-android#22]
We should create description and short description (summary) for our on Google Play. I've made sketch of them. This first one should be not longer than 80 characters and the second one - than 4000. Please tell me your changes suggestions an spelling/grammar mistakes improvments.
* * *
**Short description:**
Official FOSSASIA application for annual conference (2015 in Singapore)
* * *
**Long description:**

Official FOSSASIA application for annual conference (2015 in Singapore), which gives possibility (among others) to download current schedule and browse it offline.

Main features:
* download and browse most recent schedule off-line (phone-optimized view)
* instant search for speakers, sessions, etc.
* full-detailed information about sessions, speakers, schedule and rooms 
* simple map of FOSSASIA campus
* bookmark managment, notifications about upcoming sessions, speeches

Code (created basing on Christophe Beyls's FOSDEM app) is available at Github: https://github.com/fossasia/fossasia-companion-android

Apache License - 2015 FOSSASIA Community & contributors

* * *
@batraabhishek I would like to ask you to provide some screenshots (or video material), which we can present on Google Play.

**Comment by mariobehling** [comment]
Thanks, looks good.

**Comment by ty221** [comment]
@batraabhishek Can you post here some screenshots?

**Comment by batraabhishek** [comment]
Here you go :) Sorry for the delay. I am almost done with the App... Fixing bugs. Will upload apk soon

![screenshot_2015-03-08-19-23-09](https://cloud.githubusercontent.com/assets/3257840/6546043/e9902fa0-c5c8-11e4-84d4-85c14224391c.png)
![screenshot_2015-03-08-19-23-16](https://cloud.githubusercontent.com/assets/3257840/6546044/e9921bbc-c5c8-11e4-9093-2ebddff1a8fe.png)
![screenshot_2015-03-08-19-23-33](https://cloud.githubusercontent.com/assets/3257840/6546045/e994edba-c5c8-11e4-86d9-556f6408eecb.png)
![screenshot_2015-03-08-19-23-44](https://cloud.githubusercontent.com/assets/3257840/6546046/e9dada82-c5c8-11e4-8f98-1c70e7168c60.png)
![screenshot_2015-03-08-19-23-55](https://cloud.githubusercontent.com/assets/3257840/6546047/e9df20ba-c5c8-11e4-9b0c-5717606d4acd.png)

**Comment by ty221** [comment]
@batraabhishek Thank you very much. I am really impressed by your work. Keep it up :D
