### ISSUE TITLE
V. 0.9 App does not install on Android Cynogenmod 2.7 Motorola Defy

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia-companion-android#28]
Steps: 1) Download and safe apk to sd card
2) Install app
3) Message appears "Application not installed" (nothing else)

**Comment by ty221** [comment]
@mariobehling The most possible reason it, that application package (APK) is not signed. Android denies installing unsigned apps.

**Comment by ty221** [comment]
@mariobehling I will send you by mail the signed APK (signed by me), please check it out.
