### ISSUE TITLE
Twitter links not working

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia-companion-android#30]
It looks like a click on the twitter button does not open the browers or twitter links.
This may be because there are different formats.
Which format do you prefer in the spreadsheet?
e.g. @twittername or http://twitter.com/name

**Comment by batraabhishek** [comment]
Any format is fine, but it should be same everywhere. Though we can handle both also.

**Comment by mariobehling** [comment]
not sure, where is the link to Twitter. Does not seem to work anywhere. Can you let me know, where it should work?

**Comment by batraabhishek** [comment]
Fixed Twitter links. Supports both @twittername and url format. Changes will reflect in updated App
