### ISSUE TITLE
Add Linkedin to app

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia-companion-android#31]
We do not have a field for Linkedin in the document. I am adding this field behind the twitter field in the original document.

**Comment by batraabhishek** [comment]
@mariobehling The app tries to fetch data from spreadsheet with fixed sequence of columns. So adding new Column won't allow the app to download the data, as structure is changed. So in this case, if you need to app additional field, please add it at the end. This will allow both group of users (with old version of app, and new version of app) to use the app. Thanks for completing the Version Sheet :). I am working on all the open issues and will post a new release ASAP

**Comment by mariobehling** [comment]
Sorry, we changed the structure before you made the comment. Also some fields had be renamed. Could you implement this, please in the app? I think these should be the last changes in the structure.

**Comment by batraabhishek** [comment]
Fixed
