### ISSUE TITLE
After Clicking on Track e.g. "Web" show the track name "Track - Web", dates of track and location on top + make "Tracks" clickable

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia-companion-android#33]
e.g.
= Tracks -> Web
March 14/March 15, ACE Blk79

* Make the word "Tracks" Clickable and link to the main screen.

**Comment by batraabhishek** [comment]
How about this? Added a back button to go to main screen, Venue is too big to display in one line with dates. Suggestions?
![screenshot_2015-03-09-12-44-07](https://cloud.githubusercontent.com/assets/3257840/6551240/233096c2-c65b-11e4-9530-495193810414.png)

**Comment by mariobehling** [comment]
Yes, very good.
