### ISSUE TITLE
Implement location info/directions in map based on "version" sheet

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia-companion-android#34]
I added the venue/location information to the spreadsheet in the "version" sheet. Please check how the info can be implemented in the app.

**Comment by batraabhishek** [comment]
How about displaying an icon in ActionBar (top bar) in Track screen. On clicking it open Google Maps ?

**Comment by mariobehling** [comment]
Yes, good idea. Also the question is, if we could make the "location info" above the talks clickable.

**Comment by batraabhishek** [comment]
Yes ! Will do that

**Comment by mariobehling** [comment]
Does the map work already with you? I still see the static map picture here.

**Comment by batraabhishek** [comment]
No, static image. @mananwason is working on this I guess.

**Comment by mariobehling** [comment]
![fossasia-map](https://cloud.githubusercontent.com/assets/1583873/6553190/0953342a-c689-11e4-9bb7-79a196ac4441.png)
Here a better screenshot of the FOSSASIA venue locations. Please add.

**Comment by mananwason** [comment]
@mariobehling @batraabhishek Even though I am done with the map, I don't think it's wise to include it, as it needs 4 more permissions and we don't get a very good look of the venue as well. The location is just shown as a pointer, Maps doesn't provide a zoomed version. Also, we have to add another library, i.e. the Play services. So, it's not worth it in my view. What do you suggest?

**Comment by mariobehling** [comment]
I dont have a clear opinion. Could you offer a test apk with the map? Many people have installed Play services already. So, I think it would not be an issue.

**Comment by ty221** [comment]
Hi,
Using permissions is nothing wrong. Every body knows we need them for map
(we can write info about it in description too). IMHO Google Play is good
solution

**Comment by ty221** [comment]
I am sorry I meant Google Maps :)

**Comment by mananwason** [comment]
@mariobehling @ty221 I just meant that we are getting the same results(the view) with more number of permissions, so, I don't really see the point of adding maps. Anyways, I am trying something else, if it pans out, i'll merge it, otherwise as @mariobehling says, i'll give a test apk with the map fragment.

**Comment by mariobehling** [comment]
The difficulty is that we have two locations this time. Maybe it would be possible to define different areas on the map. Then the user touches it and the location opens in the map application. Please have a look at the spreadsheet "FOSSASIA 2015 - Talks App Sample". There is a sheet "versioning" with all the location data and map links. What do you suggest as a good way for participants?

**Comment by batraabhishek** [comment]
Implemented partial. Added a button in action bar on the screen when the track is clicked

**Comment by batraabhishek** [comment]
Completed !

**Comment by mariobehling** [comment]
Please use the new screenshot in this issue above for the map display.

**Comment by batraabhishek** [comment]
Done
