### ISSUE TITLE
Current Release not Working

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia-companion-android#35]
@ty221 
The current release is not working as we are generating the DB from the spreadsheet. We had changed the spreadsheet structure yesterday and when you released the app, it already did not worked. Please check the app in the app store.

Let's check that the app works before we release it on the app store. Cheers.

 @batraabhishek Some headings were changed as well. This should be the last major change. Could you help and fix it, please?

**Comment by batraabhishek** [comment]
Already on it :)

**Comment by batraabhishek** [comment]
Fixed current release. While updating there are few other things to update. 
In the Versioning sheet there is a column GID. This value has to be updated when any sheet is updated. Now how to get the GID ?
For any sheet, look at the URL 
It will look like this https://docs.google.com/spreadsheets/d/1tt6LXrnc_onSZEbAzzA0bZiq_mtPFNHE8a8P5a6T-tQ/edit#gid=614071948

**gid=614071948** is the GID here.

In versioning sheet add the corresponding sheet GID. This is required for the app to work. It allows dynamic track addition. I should have told this before. Sorry :)

**Comment by mariobehling** [comment]
Ok, great. Thanks for the info!
