### ISSUE TITLE
Installation Failed in Android 4.3 (GT-9300), RELEASE 0.9

### ISSUE THREAD

**Issue by tonghuix** [fossasia/fossasia-companion-android#38]
I tried install RELEASE 0.9 from Github Repo, but failed. 

Then I install from Google Play successfully. I know it is a old release. 

My Phone is Samsung GT-9300 ships Android 4.3.

**Comment by batraabhishek** [comment]
It's an unsigned built. It requires signing before it can be installed. You can download it from here 
https://play.google.com/store/apps/details?id=org.fossasia
