### ISSUE TITLE
Change color of background of start screen to red, font to white and more info about 2015

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia-companion-android#39]
To do:
* Start screen background red
* font/logo in white
* Add info below similar style on website<br>
MARCH 13TH - 15TH SINGAPORE<br>
OPENING EVENT FRIDAY MARCH 13<br>
@ BIOPOLIS MATRIX<br>
TRACKS ON SAT/SUN MARCH 14/15<br>
@ LAUNCHPAD CAMPUS IN BLK71 AND BLK79
![fossasia-squarewhite-path](https://cloud.githubusercontent.com/assets/1583873/6552935/2210b8c8-c686-11e4-8f98-84f606bddf1a.png)

**Comment by ty221** [comment]
Please reassign to me. Will improve

**Comment by ty221** [comment]
@mariobehling Do you have higher resolution image of white FOSSASIA logo (something like 1300x...)?
