### ISSUE TITLE
Person Information is NULL

### ISSUE THREAD

**Issue by mananwason** [fossasia/fossasia-companion-android#4]
Even though my google plus account is functional and It shows user is connected. It goes to the else part and says that Person Information is NULL. Please Help. Is this with everyone or just me?
![image](https://cloud.githubusercontent.com/assets/10570249/6129010/f3e6ef38-b160-11e4-8147-5270cd50d062.png)

**Comment by batraabhishek** [comment]
@mananwason  Can you please point where this code is located. I am not able to find it.

**Comment by mananwason** [comment]
@batraabhishek It's in the settiings class, there you'll easily find it.

**Comment by mananwason** [comment]
But could you get the app to work ?

**Comment by batraabhishek** [comment]
Yes, I am able to successfully build and run the app. My bad but I am still not able find the above code or Settings.java class. May be I am missing something here.

**Comment by mananwason** [comment]
I am also able to build and run the app, but after logging in nothing works
