### ISSUE TITLE
Breaks - Lunch, Coffee Break are not showing up in schedule

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia-companion-android#41]

**Comment by batraabhishek** [comment]
@mariobehling While fetching from spreadsheet to database, to avoid any dirty data(blank columns mainly) these four fields are: required, date, time, given name, topic name. So if we want to fill Lunch, Coffee Break, we have to fill **date, time, given name, topic name** fields, then it will be show up in schedule. But here is a drawback. It will end the data under Given name in speakers also :P. I will think something to fix this.

**Comment by mariobehling** [comment]
@batraabhishek Could you release a new version with the points you fixed already? Release early, release often ;-)

**Comment by batraabhishek** [comment]
@mariobehling Sure:) I see @ty221 has released a new version. I will release further version from now on :+1:

**Comment by ty221** [comment]
@batraabhishek Yes, I've released it as it contained a lot of useful changes. It will appear in Google Play in next few hours.

**Comment by batraabhishek** [comment]
@ty221 Thanks :D

**Comment by ty221** [comment]
@batraabhishek No problem :-)

**Comment by ty221** [comment]
@batraabhishek @mariobehling How about this workaround? Let us fill these places, by e.g. "!!!". Then in application verify if field is "!!!", make impossible to go to details and do not display any speaker, etc.
