### ISSUE TITLE
Clicking on a track -> Go to the first day of sessions

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia-companion-android#42]
Currently after the user clicks a track, the screen shows on most tracks "no sessions on this day" and then the user clicks again on e.g. "March 13".
Desired behaviour: The user clicks on track and gets the first day with tracks right away, e.g. March 14.
*For the Friday OpenTech track that should be March 13.

**Comment by ty221** [comment]
@batraabhishek @mariobehling If you don't mind, I can finish working on this enhancement :)

**Comment by batraabhishek** [comment]
@ty221 Sure, let me know if you face any problem
