### ISSUE TITLE
Add "Sponsors and Partners" section

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia-companion-android#46]
What do you suggest, how a sponsor and partners section can be added?

**Comment by mananwason** [comment]
Another Fragment with a list of sponsors in it or else just an image of all the sponsors logo.

**Comment by ty221** [comment]
@mananwason IMHO better idea is to add another one fragment, as we still may add new sponsors

**Comment by mananwason** [comment]
@ty221  I think you're right. We should add another fragment. I can do it.

**Comment by ty221** [comment]
@mananwason It would be nice, if you can finish work on this issue :D

**Comment by mananwason** [comment]
@mariobehling @ty221  How's this?

![screenshot8642972058743460347](https://cloud.githubusercontent.com/assets/10570249/6568308/6b7384e4-c6fb-11e4-87f4-b13d59006b14.png)
![screenshot8856506935719924265](https://cloud.githubusercontent.com/assets/10570249/6568309/6ddcf580-c6fb-11e4-86ed-5aba295bf435.png)

**Comment by mananwason** [comment]
@ty221 @mariobehling Please Reply.

**Comment by ty221** [comment]
@mananwason I like it, however in my opinion rows should have same height,
then it will look better

**Comment by mananwason** [comment]
@ty221 I'll correct it.

**Comment by ty221** [comment]
@Mananwason thank you :)

**Comment by mananwason** [comment]
Sure @ty221 :)

**Comment by mananwason** [comment]
@ty221 @mariobehling Do I need to specify the distinction between the venue and supporting partners and the title sponsers?

**Comment by mariobehling** [comment]
Yes, would be good to have that option. Could you have a look at the "FOSSASIA 2015 - Talks App Sample" spreadsheet. I made a list of items for a sponsor. It would be good if we could fill the app through the spreadsheet - just like with the talks. Any suggestions for additional fields?

**Comment by mananwason** [comment]
@mariobehling why do we need to have a sponsor column. It would be better to use logos instead of just names and for that it would be better to add images in the project only I guess.

**Comment by mariobehling** [comment]
We want the app to be flexible and if possible to be used for other events. There is one row "link to image" where the app can download the image at the beginning. Please check how this is done for speaker images. Hardcoding is not the way to go. We are looking at a flexible process.

Currently, I also do not understand, why the images are in different sizes? I mean, I guess it is different image sizes, but the size should be implemented according to the sponsors status. For the beginning (first version) I would say - all have the same size, but it is not the way I see it in the screenshots.

**Comment by mananwason** [comment]
@mariobehling I understand that you want to make the app flexible but you have to make one entry in the spreadsheet anyway. In my implementation also, we just have to put the image in the array i've made.
This also helps us because, if we set it to download every image on startup, it will take lot of time to load and specially at the time of the summit, where the bandwidth will be limited, it can get messy. Anyways the sponsors wouldn't change much I guess. What do you think ?

**Comment by RoonyH** [comment]
@mananwason Imho you can't expect end users, (organizers are end users) to edit code. And having to release a new version for each new addition of a sponser is very bad.

**Comment by batraabhishek** [comment]
@mananwason Moreover we are using Volley library, which has very efficient implementation of caching. So most wont be downloaded again and again. I agree with @RoonyH, even for small change we will have to release a new update, and most of the end-user don't update the app immediately.

**Comment by mananwason** [comment]
ok @RoonyH @batraabhishek if you say so, I just expressed my opinion. I'll change it then.

**Comment by batraabhishek** [comment]
great :) Let me know if you need any help with data fetching from spreadsheet

**Comment by mananwason** [comment]
Sure thanks :)

**Comment by mananwason** [comment]
@batraabhishek can you give my the link to the place where @mariobehling has added the link to image column

**Comment by batraabhishek** [comment]
@mananwason Its second last column in every track sheet

**Comment by mananwason** [comment]
Thanks @batraabhishek I got it. Although please point me to somewhere where you have used volley to access the data on the spreadsheet. I will understand it from there.

**Comment by batraabhishek** [comment]
Will u be using a new sheet in the doc ?

*Sent via a really tiny keyboard - please excuse the brevity of the message

**Comment by mananwason** [comment]
There is a new sheet created by @mariobehling, the sponsor sheet.

**Comment by batraabhishek** [comment]
Great! Check JsonToDatabase.java class in db package. You can see any function here. 
See this post on how to form the URL from spreadsheet.
1) Request a Volley queue
2) Make a String Request. See how it is done there.
3) You need to remove some unwanted response. Google API adds some sort of function prototype to JSON response. Use function removePaddingFromString()
4) Add to queue.
 Your request response will come in Respose Listener, handle it from there by saving it in database. You can create a table by declaring it in DatabaseHelper class. make sure you modify the database name, or every old version app will start crashing.

**Comment by mananwason** [comment]
Hi @batraabhishek. Thanks for your help. Can you please tell me what do you mean by modifying the database name. Could you elaborate ?

**Comment by batraabhishek** [comment]
@mananwason Modify line 44, DatabaseHelper.java :P A new db name will recreate the database

**Comment by mananwason** [comment]
oh ya allright. Thanks :D

**Comment by mananwason** [comment]
@batraabhishek  I finished the implementation but when I run the app, it showed me some errors in stringrequest.java(I didn't do anything to string request.java) . Can you help me with this. I googled a lot, but to no avail.
thanks

![image](https://cloud.githubusercontent.com/assets/10570249/6645175/3bc3845a-c9e0-11e4-8249-8bd2d3c1cc1f.png)

**Comment by batraabhishek** [comment]
in my cloned repo this is the constructor definition 
    `public StringRequest(String url, Listener<String> listener, ErrorListener errorListener) {
        this(Method.GET, url, listener, errorListener);
    }`

**Comment by mananwason** [comment]
But when I add the errorlistener, then I get the following error, but the same code you've written in the fetchtrackurl is perfectly fine. Why is that so ?
![image](https://cloud.githubusercontent.com/assets/10570249/6650645/ce04bbd6-ca44-11e4-97ce-816df62eab8f.png)

**Comment by mananwason** [comment]
@mariobehling @ty221 @batraabhishek  Can you suggest a default image for sponsor ?

**Comment by ty221** [comment]
@mananwason If there is no logo we can add grey FOSSASIA logo with small additional text "Sponsor" below.

**Comment by batraabhishek** [comment]
Yea, nice idea @ty221 . @mananwason You can use something similar to this 
![untitled-2](https://cloud.githubusercontent.com/assets/3257840/6830229/76a426f8-d33e-11e4-85e0-a1cf9bfbb4c4.png)

**Comment by mananwason** [comment]
Yeah good idea @ty221. I will use this,

**Comment by mananwason** [comment]
@batraabhishek I am getting the following error can you please tell me what can be the reason
![image](https://cloud.githubusercontent.com/assets/10570249/6830539/58709976-d340-11e4-9baf-6c8d23424bdb.png)
 This is what I've done to create the table 
![image](https://cloud.githubusercontent.com/assets/10570249/6830565/a31fe436-d340-11e4-867b-7656c5046804.png)

**Comment by ty221** [comment]
Where do you execute `TABLE_SPONSOR` ?

**Comment by mananwason** [comment]
In the oncreate method

**Comment by mananwason** [comment]
Thanks @ty221I figured it out. I forgot to add the queries to the volley queue.

**Comment by mananwason** [comment]
@ty221 @mariobehling  I have implemented the sponsor and partner section but I am not doing anything on clicking the sponsor image. What should I do with it ?
![screenshot5572327979791105362](https://cloud.githubusercontent.com/assets/10570249/6845348/c5334f9c-d3d9-11e4-9980-a48aa33a33bc.png)

**Comment by ty221** [comment]
Nice. Thanks. How about opening sponsor's website?

**Comment by mananwason** [comment]
Intent or inside the app only ?

**Comment by ty221** [comment]
I think Intent is better in this case.

czw., 26 mar 2015 o 14:44 użytkownik Manan Wason <notifications@github.com>
napisał:

**Comment by mananwason** [comment]
Yeah I was also thought so. I'll do it and create the pull request today itself. Many thanks

**Comment by ty221** [comment]
@mananwason Thank you. One more suggestions: can you change title in the top from "Sponsor" to "Sposnors" ?

**Comment by mananwason** [comment]
Oh yeah sure @ty221 I am sorry for the mistake !!  :D

**Comment by ty221** [comment]
No problem, thanks :)

**Comment by mananwason** [comment]
@mariobehling @ty221  Please close this.

**Comment by ty221** [comment]
@mananwason Why? It's still remaining unimplemented...

**Comment by mananwason** [comment]
@ty221 see my latest PR, it's done there. What else is unimplemented?

**Comment by mananwason** [comment]
@ty221 see my latest PR, it's done there. What else is unimplemented?

**Comment by mananwason** [comment]
@ty221 see my latest PR, it's done there. What else is unimplemented?

**Comment by mananwason** [comment]
@ty221 see my latest PR, it's done there. What else is unimplemented?

**Comment by ty221** [comment]
@mananwason Huh, sorry. Merging + closing

**Comment by mananwason** [comment]
No problem @ty221 :)
