### ISSUE TITLE
Code refactoring from Fosdem to Fossasia

### ISSUE THREAD

**Issue by batraabhishek** [fossasia/fossasia-companion-android#5]
I would like to work on code refactoring from Fosdem to Fossaisa. This will also help me in understanding the code flow of the app, thus it will become easy for me to implement new features.

**Comment by mariobehling** [comment]
Yes, great. Please feel free to work on it. A question is, how could we merge improvements from the original app in future? Or should we just move forward and develop a separate code base completely to keep it easier for us?

**Comment by batraabhishek** [comment]
I might be wrong here, it will become difficult with time to merge code from the original repo. as we might end up implementing our own improvements. Even refactoring will create a lot of merge conflicts. So according to me the best options is maintain a separate codebase. And porting any major improvement manually from the original repo. to fossasia repo.

**Comment by mananwason** [comment]
Yeah @mariobehling I also agree with @batraabhishek, It will be much easier to maintain a separate codebase. Maybe in separate branches.

**Comment by ty221** [comment]
That is good idea. Let us create separate branch, work on it, and when it will be working properly - eventually merge it.

**Comment by mariobehling** [comment]
Yeah, good idea. Feel free to start working on it and merging code here.

**Comment by batraabhishek** [comment]
Sure. Thanks
