### ISSUE TITLE
How to export all events to a calendar e.g. ical?

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia-companion-android#51]
Request from Ujjwal: I know it's a lot of work but it would great if you guys could create the entire schedule as a calendar file. That would provide a great way for people to download it and be able to checkout all the events including ones that clash on their mobile.
What are your ideas?

**Comment by batraabhishek** [comment]
Yeah good idea ! If any one is willing to do this, they can refer this library http://ical4j.sourceforge.net/introduction.html, a bit busy right now (college project submission), will again start working on the app in few hours. Will generate ical file ASAP

**Comment by ujjwalt** [comment]
That looks great. Any Java programmers here :wink:

**Comment by mananwason** [comment]
Hi @ujjwalt. I am a Java programmer

**Comment by batraabhishek** [comment]
Me too !

**Comment by ujjwalt** [comment]
@mananwason and @batraabhishek Can anyone of you quickly produce iCal files for the FOSSASIA schedule?

**Comment by batraabhishek** [comment]
@ujjwalt  Starting now...

**Comment by ujjwalt** [comment]
Awesome!

**Comment by batraabhishek** [comment]
@ujjwalt I have compiled an initial version using ical4j library ,Download as raw file https://github.com/fossasia/fossasia-companion-android/blob/master/Event%20to%20iCalendar%20convertor/mycalendar.ics

**Comment by batraabhishek** [comment]
@ujjwalt Do take care of time zone diff (if you are not in singapore) ;)

**Comment by ujjwalt** [comment]
This looks awesome! Thanks a ton! I've not verified it yet but it looks
right.

**Comment by ujjwalt** [comment]
Ok this is incorrect unfortunately. I know it because I can't find my talk :tongue:

**Comment by batraabhishek** [comment]
Oh! Whats your talk and track ?

**Comment by batraabhishek** [comment]
@ujjwalt I guess the calender file was created before updating the spreedsheet. I recreated the file and Your talk is there :)

![screen shot 2015-03-12 at 12 33 11 am](https://cloud.githubusercontent.com/assets/3257840/6604625/af07402e-c84f-11e4-9a16-2dbd854b59de.png)

**Comment by ty221** [comment]
@batraabhishek I belive you :-) Closing this issue...

**Comment by mariobehling** [comment]
Hi. Sorry, I did not get it yet: How can I generate a new ical every time the db is updated? Is it possible to export it from the app? What are the steps?

**Comment by ujjwalt** [comment]
@batraabhishek I think you haven't uploaded the new file

**Comment by batraabhishek** [comment]
Uploaded a new file. @mariobehling Its a separate java project that created a iCalendar file. I didnot implemented in the app, because it will generate iCalendar file on every device running the app.

**Comment by mariobehling** [comment]
Ok, understand, could you add the ical in the FOSSASIA site, please? Just put it in the main directory here, please: https://github.com/fossasia/fossasia15

**Comment by batraabhishek** [comment]
Sure ! Cloning repo. :)

Regards,
Abhishek Batra
+91-8754758134
LinkedIn <https://www.linkedin.com/in/batraabhishek>

**Comment by batraabhishek** [comment]
@mariobehling  Done ... Added PR.

**Comment by mariobehling** [comment]
What time zone did you set the calendar? I have set everything here to Singapore time zone and it shows, that things are starting at 6.30. Any idea?

**Comment by mariobehling** [comment]
![icaltimezone](https://cloud.githubusercontent.com/assets/1583873/6614931/3c5cdd3c-c8da-11e4-9da1-73f5408c4f48.png)

**Comment by batraabhishek** [comment]
@mariobehling I am not able to figure out whats the problem with code right now. How about a time independent Calendar for now. Timing will be fixed irrespective of time zone. Suggestions ?

**Comment by mariobehling** [comment]
Yes, good idea. I just thought you had set it maybe to your time zone and that would be easy to fix. Timezone-Independent calendar sounds like a good idea.

**Comment by batraabhishek** [comment]
Cool ! Created a PR https://github.com/fossasia/fossasia15/pull/42
