### ISSUE TITLE
Implement a "Venue Location" page to be accessed from the "talks pages"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia-companion-android#53]
Currently the Link to the venue location of a talk directs to a talk page. It would be good, if I could see the address and "How to get there" myself first, before being directed to a map. 

Please implement a venue location page that can be accessed from the link and include information from the spreadsheet, such as:
Venue Name<br>
Room<br>
How to get here<br>
Map	URL<br>
Link URL<br>
Address<br>

**Comment by sagarpatidar** [comment]
I have started working on this. I am just wondering from where can I get the "spreadsheet" to show data. Please help me out.

**Comment by sagarpatidar** [comment]
Created the pull request.
https://github.com/fossasia/fossasia-companion-android/pull/55
Check it out.
Cheers!

**Comment by batraabhishek** [comment]
Added location data to dialog. Changed a little formatting to support app theme.

![venue](https://cloud.githubusercontent.com/assets/3257840/6615958/de63ee7e-c8ce-11e4-9865-98a1fd5254fa.jpg)

**Comment by batraabhishek** [comment]
Added location data to the dialog, changed a little formatting to match app theme
![sc](https://cloud.githubusercontent.com/assets/3257840/6616018/9b50aaae-c8cf-11e4-91ab-807170abb4e2.jpg)

**Comment by sagarpatidar** [comment]
Looks good. Though, I would suggest to change the background of dialog title. Red color of "okay"(Button) contradicts with red color of the dialog title which is not a button. You might want to rethink upon it.

**Comment by batraabhishek** [comment]
@sagarpatidar Okay... I will make some changes to give it a button look.
