### ISSUE TITLE
empty tracks on some devices

### ISSUE THREAD

**Issue by silbermantel** [fossasia/fossasia-companion-android#73]
Selecting the ots track opentech1 shows no entries on a moto g with android 4.4.4(slimkat) while a nexus  7(tilapia) with 4.4.4(slink at) shows all results. This occurs on several tracks, reloading and restarting did not help

**Comment by mariobehling** [comment]
Seems, it was an issue with the JSON. Works again now. Closing this issue. Please add a comment, if issue is still happening.
