### ISSUE TITLE
README file should be updated

### ISSUE THREAD

**Issue by ty221** [fossasia/fossasia-companion-android#8]
README file contains old information, it should be updated with info:

1. This is app of FOSSASIA Event and it is basing on FOSDEM app.
2. List of contributors and used libraries should be updated.
3. Links to Google Play should be currently removed, links to FOSDEM changed to FOSSASIA.

**Comment by mananwason** [comment]
Readme file is updated. Just review it once and when it's uploaded on play store, we can update the Play Store link as well

**Comment by ty221** [comment]
@mananwason Thank you for your changes, now README file seems to be ok.

**Comment by mananwason** [comment]
Welcome @ty221
